[package]
name = "promocode-server"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true
authors.workspace = true

[dependencies]
actix-web = "4.5"
clap = { version = "4.4", features = ["derive"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

promocode-models = { path = "../promocode-models" }
promocode-util = { path = "../promocode-util" }
