[package]
name = "promocode-server"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true
authors.workspace = true

[dependencies]
actix = "0.13.2"
actix-web = "4.5"
futures = "0.3"
time = "0.3"

clap = { version = "4.4", features = ["derive", "env"] }

env_logger = "0.11"
log = "0.4"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"

promocode-models = { path = "../promocode-models" }
promocode-util = { path = "../promocode-util" }
